Repository openelb/console, pull requests merged in 2022-12, with the labels that each got.

#14 chore: add build tools
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  docs/code-of-conduct.md
  docs/development-workflow.md
  hack/docker_build.sh
  hack/docker_build_multiarch.sh
  nginx-configmap.yaml
Labels: lgtm, approved, size/L

#15 chore: update deploy files
  README.md
  deploy/Dockerfile
  deploy/console.yaml
  deploy/default.conf
Labels: lgtm, approved, size/L

#16 chore: Update README.md file
  README.md
Labels: lgtm, approved, size/M

#17 doc: update readme
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  deploy/console.yaml
Labels: kind/documentation, lgtm, approved, size/L
